services:
  nhtsa-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NHTSA_API_BASE_URL=https://vpic.nhtsa.dot.gov/api
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      # For development: mount src directory for hot-reloading
      # Comment out in production
      - ./src:/app/src
